version: '3.3'

services:
  mysql: 
    image: mysql:5.7
    container_name: app-devops_db
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: ./env/mysql.env

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "9101:15692"  # metrics

  app-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"  # Also has /metrics
    env_file: ./env/python.env

  app-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: app-node
    depends_on:
      - rabbitmq
      - mysql
    env_file: ./env/node.env

  mysql-monitor:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"  # metrics
    depends_on:
      - mysql
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    env_file: ./env/mysql_monitor.env
